import { type MediaItem } from '../types';

export const sampleMovies: MediaItem[] = [
    {
        id: '1',
        libraryId: '1',
        title: 'The Witcher',
        sortTitle: 'Witcher, The',
        year: 2019,
        dateAdded: '2024-01-15',
        posterPath: 'https://image.tmdb.org/t/p/w500/7vjaCdMw15FEbXyLQTVa04URsPm.jpg',
        backdropPath: 'https://image.tmdb.org/t/p/original/jBJWaqoSCiARWtfV0GlqHrcdidd.jpg',
        duration: '1h 2m',
        quality: '4K',
        genres: ['Fantasy', 'Action', 'Adventure'],
        rating: 'TV-MA',
        progress: 65,
        description: 'Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.'
    },
    {
        id: '2',
        libraryId: '1',
        title: '28 Years Later',
        sortTitle: '28 Years Later',
        year: 2025,
        dateAdded: '2024-01-20',
        posterPath: 'https://image.tmdb.org/t/p/w500/edDJVbjzFPkJc92pLlJfTBdJm8F.jpg',
        backdropPath: 'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
        duration: '2h 15m',
        quality: '4K',
        genres: ['Horror', 'Thriller', 'Sci-Fi'],
        rating: 'R',
        description: 'Nearly three decades after the rage virus escaped, the infected have evolved and cities are beginning to rise from the ashes.'
    },
    {
        id: '3',
        libraryId: '1',
        title: 'Futurama',
        sortTitle: 'Futurama',
        year: 1999,
        dateAdded: '2024-01-18',
        posterPath: 'https://image.tmdb.org/t/p/w500/7RRHbCUtAsVmKI6FEMzZB6Re88P.jpg',
        backdropPath: 'https://image.tmdb.org/t/p/original/gxQ3zSfe61kN3WeDgXTP24ZqLVT.jpg',
        duration: '22m',
        quality: 'HD',
        genres: ['Comedy', 'Animation', 'Sci-Fi'],
        rating: 'TV-14',
        progress: 42,
        description: 'Philip J. Fry, a pizza delivery boy, is accidentally frozen in 1999 and thawed out on New Year\'s Eve 2999.'
    },
    {
        id: '4',
        libraryId: '1',
        title: 'Austin Powers',
        sortTitle: 'Austin Powers',
        year: 1997,
        dateAdded: '2024-01-10',
        posterPath: 'https://image.tmdb.org/t/p/w500/5uD4dxNX8JKFjWKYMHyOsqhi5pN.jpg',
        backdropPath: 'https://image.tmdb.org/t/p/original/fE6p55wJpAWe0k3SXSaRfZ4UvSW.jpg',
        duration: '1h 34m',
        quality: 'HD',
        genres: ['Comedy', 'Crime'],
        rating: 'PG-13',
        description: 'A world-class playboy and part-time secret agent from the 1960s emerges after thirty years in a cryogenic state to battle with his nemesis Dr. Evil.'
    },
    {
        id: '5',
        libraryId: '1',
        title: 'Odienissimo',
        sortTitle: 'Odienissimo',
        year: 2024,
        dateAdded: '2024-01-22',
        posterPath: 'https://image.tmdb.org/t/p/w500/qVJJbirRHu6YEm33OdwKr8p5AWJ.jpg',
        backdropPath: 'https://image.tmdb.org/t/p/original/hOPb0tAMpIvFUIsdJPCdWm64R3k.jpg',
        duration: '1h 45m',
        quality: '4K',
        genres: ['Comedy', 'Drama'],
        rating: 'NR',
        description: 'A touching comedy-drama about family bonds and second chances.'
    },
    {
        id: '6',
        libraryId: '1',
        title: 'Monty Python Live (Mostly)',
        sortTitle: 'Monty Python Live (Mostly)',
        year: 2014,
        dateAdded: '2024-01-12',
        posterPath: 'https://image.tmdb.org/t/p/w500/xOMIGj4516LkFJNfCgJxT1FBJ0U.jpg',
        backdropPath: 'https://image.tmdb.org/t/p/original/9guoVF7zayiiUq5ulKQpt375VIy.jpg',
        duration: '2h 15m',
        quality: 'HD',
        genres: ['Comedy'],
        rating: 'NR',
        description: 'The legendary comedy troupe reunites for one last show, performing their greatest sketches.'
    },
    {
        id: '7',
        libraryId: '1',
        title: 'Terrifier 3',
        sortTitle: 'Terrifier 3',
        year: 2024,
        dateAdded: '2024-01-25',
        posterPath: 'https://image.tmdb.org/t/p/w500/7jFY1FpZXkYaVHvCKTU6kPPfqQR.jpg',
        backdropPath: 'https://image.tmdb.org/t/p/original/18TSJF1WLA4CkymvVUcKDBwUJ9F.jpg',
        duration: '2h 5m',
        quality: '4K',
        genres: ['Horror', 'Thriller'],
        rating: 'R',
        description: 'Art the Clown is set to unleash chaos on the unsuspecting residents of Miles County as they peacefully drift off to sleep on Christmas Eve.'
    },
    {
        id: '8',
        libraryId: '1',
        title: 'The Lure',
        sortTitle: 'Lure, The',
        year: 2015,
        dateAdded: '2024-01-08',
        posterPath: 'https://image.tmdb.org/t/p/w500/qzf3dDqmVBeLyXdExCjDhGJcIWb.jpg',
        backdropPath: 'https://image.tmdb.org/t/p/original/bUJGD4fStO1EyVwvxsL7i8HqGLM.jpg',
        duration: '1h 32m',
        quality: 'HD',
        genres: ['Horror', 'Musical', 'Fantasy'],
        rating: 'NR',
        description: 'Two mermaid sisters leave the ocean to pursue their dreams in Warsaw, joining a rock band and navigating the human world.'
    }
];

export const sampleTVShows: MediaItem[] = [
    {
        id: '9',
        libraryId: '1',
        title: 'The Name of the Rose',
        sortTitle: 'Name of the Rose, The',
        year: 2019,
        dateAdded: '2024-01-05',
        posterPath: 'https://image.tmdb.org/t/p/w500/7WPcP6QRRz0BnRAg2AqkCrzCMNu.jpg',
        backdropPath: 'https://image.tmdb.org/t/p/original/s6ASpNWsMPdmcIdoHsKcQYl7jrR.jpg',
        duration: '52m',
        quality: 'HD',
        genres: ['Mystery', 'Drama', 'Thriller'],
        rating: 'TV-MA',
        progress: 78,
        description: 'In 1327, Franciscan monk William of Baskerville and his novice Adso of Melk investigate a series of mysterious deaths in a medieval abbey.'
    },
    {
        id: '10',
        libraryId: '1',
        title: "Jacob's Wife",
        sortTitle: "Jacob's Wife",
        year: 2021,
        dateAdded: '2024-01-14',
        posterPath: 'https://image.tmdb.org/t/p/w500/sJNJkorHfHPBNTzl8KzcUPcVZGg.jpg',
        backdropPath: 'https://image.tmdb.org/t/p/original/mGW1Z1xjaKbLFgUamM0WEqzwBLv.jpg',
        duration: '1h 37m',
        quality: 'HD',
        genres: ['Horror', 'Thriller'],
        rating: 'R',
        description: 'Anne is married to a small-town minister and feels her life has been shrinking. After a chance encounter, she begins a transformation that brings her new appetites.'
    },
    {
        id: '11',
        libraryId: '1',
        title: 'Bottle Shock',
        sortTitle: 'Bottle Shock',
        year: 2008,
        dateAdded: '2024-01-11',
        posterPath: 'https://image.tmdb.org/t/p/w500/n6L5S4eGhqBnMmU2evZHF9Fb4Qr.jpg',
        backdropPath: 'https://image.tmdb.org/t/p/original/82ZAx1EvqiSs4F9WjFwDdBJxGT3.jpg',
        duration: '1h 50m',
        quality: 'HD',
        genres: ['Comedy', 'Drama'],
        rating: 'PG-13',
        description: 'The story of the early days of California wine making featuring the now infamous Paris wine tasting of 1976.'
    }
];
