using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using SoftMedia.Server.Data;
using SoftMedia.Server.Helpers;
using SoftMedia.Server.Models;
using SoftMedia.Server.Services.Abstractions;
using SoftMedia.Server.Services.Media;
using SoftMedia.Server.Services.Metadata;

namespace SoftMedia.Server.Services.Scanning;

/// <summary>
/// Scanner for movie libraries. Flat structure with metadata enrichment.
/// </summary>
public class MovieScanner : BaseMediaScanner
{
    private readonly IMediaAnalysisService _mediaAnalysisService;

    public override LibraryType SupportedType => LibraryType.Movie;
    public override string[] SupportedExtensions => SoftMedia.Server.Constants.MediaExtensions.Video;
    public override string DisplayName => "Movie Scanner";

    public MovieScanner(
        IServiceScopeFactory scopeFactory,
        ILogger<MovieScanner> logger,
        IMediaNotificationService notificationService,
        IMediaAnalysisService mediaAnalysisService,
        IMetadataQueue metadataQueue)
        : base(scopeFactory, logger, notificationService, metadataQueue)
    {
        _mediaAnalysisService = mediaAnalysisService;
    }

    /// <summary>
    /// Process a single video file as a movie.
    /// </summary>
    protected override async Task<ScanOperationResult> ProcessFileAsync(
        AppDbContext context,
        FileDiscoveryResult file,
        MediaItem? existing,
        Library library,
        CancellationToken cancellationToken)
    {
        var filePath = file.Path;
        try
        {
            // Parse title and year from filename
            var parsed = FileNameParser.ParseMovie(filePath);
            var title = parsed.Title;
            var year = parsed.Year;

            if (string.IsNullOrEmpty(title))
                title = Path.GetFileNameWithoutExtension(filePath);

            // Create or update movie
            var isNew = existing == null;
            var movie = existing ?? new MediaItem { LibraryId = library.Id };

            movie.Title = title;
            movie.SortTitle = MediaStringHelpers.GetSortTitle(title);
            movie.Path = filePath;
            movie.Type = MediaType.Movie;
            movie.Year = year;
            movie.Size = file.Size;
            movie.DateModified = file.LastWriteUtc;

            // Delegate technical analysis to MediaAnalysisService (Smart Probe)
            var refreshMode = isNew ? MetadataRefreshMode.Full : MetadataRefreshMode.Missing;
            await _mediaAnalysisService.AnalyzeAsync(movie, filePath, refreshMode, cancellationToken);

            if (isNew)
            {
                // Assign ID early if needed for queue? 
                // Entity Framework generates ID on Add? No, usually Guid is generated by client or constructor.
                // MediaItem constructor generates Id? Check Source. 
                // If not, we should generate it.
                if (movie.Id == Guid.Empty) movie.Id = Guid.NewGuid();

                context.MediaItems.Add(movie);

                _logger.LogDebug("[MovieScanner] Added movie: {Title} ({Year})", title, year);
                return new ScanOperationResult(ScanResult.New, movie.Id, EnqueueMetadata: true);
            }
            else
            {
                // Check if metadata needs refresh
                var needsEnrichment = MetadataEnrichmentPolicy.NeedsEnrichment(existing!, _strictEnrichment);

                if (needsEnrichment)
                {
                    _logger.LogDebug("[MovieScanner] Queued metadata enrichment: {Title}", title);
                    return new ScanOperationResult(ScanResult.Updated, movie.Id, EnqueueMetadata: true);
                }
                else
                {
                    _logger.LogDebug("[MovieScanner] Updated movie: {Title}", title);
                    return new ScanOperationResult(ScanResult.Updated, movie.Id, EnqueueMetadata: false);
                }
            }
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "[MovieScanner] Error processing file: {FilePath}", filePath);
            return new ScanOperationResult(ScanResult.Skipped);
        }
    }
}
